services:
    postgres:
      image: postgres
      environment:
        POSTGRES_USER: qweqwe
        POSTGRES_PASSWORD: eqwqe
        POSTGRES_DB: eqwewq
      volumes:
        - postgres_data:/var/lib/postgresql/data
      ports:
        - "5439:5432"
  
    redis:
      image: redis
      volumes:
        - redis_data:/data
      ports:
        - "6379:6379"
  
volumes:
    postgres_data:
    redis_data: