# Generated by Django 5.2.1 on 2025-07-02 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Мужчина'), ('female', 'Женщина')], editable=False, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='is_complete',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='name',
            field=models.CharField(default='Model', max_length=100, verbose_name='Имя аватара'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='trigger_phrase',
            field=models.CharField(default='Уникальная тригер-фраза для API LoRA', max_length=100, verbose_name='Уникальная тригер-фраза для API LoRA'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatars', to='database.user', verbose_name='Чей аватар'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='metadata',
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name='styles',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='styles', to='database.categories', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='user',
            name='current_avatar_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_pay_error_avatar',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='referrer_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='database.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='refferal_link',
            field=models.CharField(blank=True, editable=False, null=True),
        ),
    ]
