# Generated by Django 5.2.1 on 2025-05-31 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1024)),
                ('price_balance', models.IntegerField()),
                ('count_usage', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='refferal_balance',
            field=models.IntegerField(default=0),
        ),
    ]
