# Generated by Django 5.2.1 on 2025-05-31 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_promocode_user_refferal_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='price_balance',
        ),
        migrations.AddField(
            model_name='categories',
            name='name',
            field=models.CharField(default='without name', max_length=258),
        ),
        migrations.AddField(
            model_name='promocode',
            name='count_generations',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='styles',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='styles', to='database.categories'),
        ),
        migrations.AddField(
            model_name='styles',
            name='name',
            field=models.CharField(default='without name', max_length=258),
        ),
        migrations.AddField(
            model_name='user',
            name='referrer_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='database.user'),
        ),
    ]
