# Generated by Django 5.2.1 on 2025-05-31 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_photoformat_remove_promocode_price_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='generation_count',
            field=models.IntegerField(default=0),
        ),
    ]
