# Generated by Django 5.2.1 on 2025-05-31 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_user_generation_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='refferal_link',
            field=models.CharField(blank=True, null=True),
        ),
    ]
