# Generated by Django 5.2.1 on 2025-06-03 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_user_refferal_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Model', max_length=100)),
                ('dataset_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('element_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('element_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Мужчина'), ('female', 'Женщина')], max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('api_credit_cost', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Формат',
                'verbose_name_plural': 'Форматы фото',
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(help_text='ID платежа в ЮKassa', max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Сумма платежа', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('succeeded', 'Успешно'), ('canceled', 'Отменен')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Платеж Юкасса',
                'verbose_name_plural': 'Платежи Юкасса',
            },
        ),
        migrations.DeleteModel(
            name='PhotoFormat',
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='promocode',
            options={'verbose_name': 'Промокод', 'verbose_name_plural': 'Промокоды'},
        ),
        migrations.AlterModelOptions(
            name='styles',
            options={'verbose_name': 'Стиль', 'verbose_name_plural': 'Стили'},
        ),
        migrations.AlterModelOptions(
            name='tariffs',
            options={'verbose_name': 'Пакет', 'verbose_name_plural': 'Пакеты'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='avatar',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatars', to='database.user'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='database.user'),
        ),
    ]
