# Generated by Django 5.2.1 on 2025-06-03 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_avatar_paymentrecord_delete_photoformat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo_format',
            field=models.CharField(blank=True, choices=[('1:1', '1:1'), ('3:4', '3:4'), ('9:16', '9:16'), ('16:9', '16:9')], max_length=15, null=True),
        ),
    ]
