# Generated by Django 5.2.1 on 2025-06-05 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_user_photo_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPromocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_promocode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promocodes', to='database.promocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_users', to='database.user')),
            ],
        ),
    ]
