# Generated by Django 5.2.1 on 2025-06-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_mailing_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo_format',
            field=models.CharField(choices=[('1:1', '1:1'), ('3:4', '3:4'), ('9:16', '9:16'), ('16:9', '16:9')], default='1:1', max_length=15),
        ),
    ]
