# Generated by Django 5.2.1 on 2025-06-08 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_alter_user_photo_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='refferal_balance',
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(default='without name', max_length=258, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Сумма платежа', max_digits=10, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидание'), ('succeeded', 'Успешно'), ('canceled', 'Отменен')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='database.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(max_length=1024, verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='count_generations',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество генераций'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='count_usage',
            field=models.IntegerField(verbose_name='Сколько раз можно использовать'),
        ),
        migrations.AlterField(
            model_name='styles',
            name='name',
            field=models.CharField(default='without name', max_length=258, verbose_name='Название стиля'),
        ),
        migrations.AlterField(
            model_name='tariffs',
            name='cost',
            field=models.PositiveIntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='tariffs',
            name='count_generations',
            field=models.PositiveIntegerField(verbose_name='Количество генераций'),
        ),
        migrations.AlterField(
            model_name='tariffs',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=64, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='generation_count',
            field=models.IntegerField(default=0, verbose_name='Количество генераций'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=64, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo_format',
            field=models.CharField(choices=[('1:1', '1:1'), ('3:4', '3:4'), ('9:16', '9:16'), ('16:9', '16:9')], default='1:1', max_length=15, verbose_name='Формат фото'),
        ),
    ]
