# Generated by Django 5.2.1 on 2025-06-13 09:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_remove_user_refferal_balance_alter_categories_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserArchive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telegram_user_id', models.BigIntegerField(unique=True)),
                ('archive_file', models.FileField(upload_to='archives/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='avatar',
            options={'verbose_name': 'Аватар', 'verbose_name_plural': 'Аватары'},
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='api_credit_cost',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='dataset_id',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='element_id',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='element_name',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='is_active',
        ),
        migrations.AddField(
            model_name='avatar',
            name='api_name',
            field=models.CharField(default='Уникальное имя для API LoRA', editable=False, max_length=150, unique=True, verbose_name='Уникальное имя для API LoRA'),
        ),
        migrations.AddField(
            model_name='avatar',
            name='trigger_phrase',
            field=models.CharField(default='Уникальная тригер-фраза для API LoRA', max_length=100),
        ),
        migrations.AddField(
            model_name='styles',
            name='capture_for_lora',
            field=models.TextField(blank=True, null=True, verbose_name='Промо для генерирования'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
