# Generated by Django 5.2.1 on 2025-06-13 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_userarchive_alter_avatar_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
