# Generated by Django 5.2.1 on 2025-06-13 09:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_delete_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Model', max_length=100)),
                ('api_name', models.CharField(default='Уникальное имя для API LoRA', editable=False, max_length=150, unique=True, verbose_name='Уникальное имя для API LoRA')),
                ('is_complete', models.BooleanField(default=False)),
                ('trigger_phrase', models.CharField(default='Уникальная тригер-фраза для API LoRA', max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Мужчина'), ('female', 'Женщина')], max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatars', to='database.user')),
            ],
            options={
                'verbose_name': 'Аватар',
                'verbose_name_plural': 'Аватары',
            },
        ),
    ]
