# Generated by Django 5.2.1 on 2025-06-13 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Styles',
        ),
    ]
