# Generated by Django 5.2.1 on 2025-06-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_styles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_avatar_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
