# Generated by Django 5.2.1 on 2025-06-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_user_current_avatar_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo_format',
            field=models.CharField(default='square_hd', max_length=15, verbose_name='Формат фото'),
        ),
    ]
