# Generated by Django 5.2.1 on 2025-06-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0018_alter_user_photo_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_pay_error_avatar',
            field=models.BooleanField(default=False),
        ),
    ]
